[package]
name = "cosmic-settings-system"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = "5.1.6"
const_format = "0.2.34"
concat-in-place = "1.1.0"
sysinfo = "0.31.4"
memchr = "2.7.4"

[dependencies.bumpalo]
version = "3.17.0"
features = ["collections"]
